# Generated by Django 3.2.4 on 2021-06-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_transactions', '0002_rename_comments_reviews_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user_comment',
            field=models.TextField(max_length=300),
        ),
    ]
