# Generated by Django 3.2.4 on 2021-06-30 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_transactions', '0003_alter_reviews_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user_comment',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='created_on',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
