# Generated by Django 3.2.4 on 2021-07-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_transactions', '0006_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
