# Generated by Django 3.2.4 on 2021-07-06 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_transactions', '0008_user_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_booking',
            old_name='room_type',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user_booking',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user_booking',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_booking',
            name='date1',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user_booking',
            name='date2',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
