# Generated by Django 3.2.4 on 2021-07-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_transactions', '0011_user_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
